# Generated by Django 4.0.5 on 2022-07-09 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255)),
                ('full_bio', models.TextField(blank=True)),
                ('personal_interests', models.TextField(blank=True)),
                ('family_interests', models.TextField(blank=True)),
                ('available_times', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('unread', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='pnp_app.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pnp_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('0-12 mos', '0-12 mos'), ('1-3 yrs', '1-3 yrs'), ('3-5 yrs', '3-5 yrs'), ('elementary', 'elementary'), ('middle school', 'middle school'), ('high school', 'high school')], max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to answer', 'Prefer not to answer')], max_length=255)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='pnp_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(to='pnp_app.profile')),
            ],
        ),
    ]
